"use client";

import React, { useState, useRef, useCallback } from 'react';
import { initialReportState, ReportState } from '@/lib/report-data';
import ReportHeader from './ReportHeader';
import MetaBar from './MetaBar';
import ActionBar from './ActionBar';
import SummarySection from './SummarySection';
import PartASection from './PartASection';
import PartBSection from './PartBSection';
import ConclusionSection from './ConclusionSection';
import ImageComposer from './ImageComposer';

export default function ReportPage() {
  const [reportData, setReportData] = useState<ReportState>(initialReportState);
  const reportContainerRef = useRef<HTMLDivElement>(null);

  const updateField = useCallback((key: string, value: any) => {
    setReportData((prev) => ({ ...prev, [key]: value }));
  }, []);

  const handleReset = useCallback(() => {
    // A confirmation dialog is a good UX practice for destructive actions
    if (window.confirm('Are you sure you want to reset all fields and images? This action cannot be undone.')) {
      setReportData(initialReportState);
    }
  }, []);

  const getReportTextContent = () => {
    return Object.entries(reportData)
      .filter(([key, value]) => typeof value === 'string' && !key.startsWith('composer-') && !value.startsWith('<'))
      .map(([key, value]) => `${key.replace(/-/g, ' ')}: ${value}`)
      .join('\n');
  }

  const getChartDescriptions = () => {
    // This is a simplified way to get chart titles. In a more complex app, this could be more dynamic.
    const chartKeys = Object.keys(reportData).filter(key => reportData[key] === null && !key.startsWith('composer'));
    return chartKeys.map(key => key.replace(/-/g, ' ')).join(', ');
  }

  return (
    <>
      <ActionBar onReset={handleReset} reportRef={reportContainerRef} />
      <div className="report-container" ref={reportContainerRef}>
        <ReportHeader data={reportData} updateField={updateField} />
        <MetaBar data={reportData} updateField={updateField} />
        
        <div className="report-section" id="composer">
          <h2>🖼️ Image/Text Composer</h2>
          <div className="chart-card">
            <ImageComposer 
              imageData={reportData['composer-image']} 
              overlays={reportData['composer-overlays']}
              onImageChange={(img) => updateField('composer-image', img)}
              onOverlaysChange={(overlays) => updateField('composer-overlays', overlays)}
            />
          </div>
        </div>

        <ConclusionSection
          data={reportData}
          updateField={updateField}
          getReportTextContent={getReportTextContent}
          getChartDescriptions={getChartDescriptions}
        />
        <SummarySection data={reportData} updateField={updateField} />
        <PartASection data={reportData} updateField={updateField} />
        <PartBSection data={reportData} updateField={updateField} />
        <footer className="report-footer">
          Energy Bill Audit Report generated by Energy Audit Pro.
        </footer>
      </div>
    </>
  );
}
